language: node_js
node_js:
  - "10"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t flowerlang/api:latest .
  - docker push flowerlang/api:latest
